Vagrant.configure('2') do |config|
  config.vm.box = 'ubuntu/trusty64'
  config.vm.network :private_network, ip: '10.10.10.10'
  config.vm.provision "shell",
    inline: "echo \"echo root profile processed\" > ~/.bash_profile"
end
