- hosts: all
  become: yes
  become_method: sudo
  vars:
    node_app_path: /mnt/node-app.js
  tasks:
    - name: ensure apt cache is updated
      apt:
        update_cache: yes

    - name: ensure apt packages are installed
      apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - nodejs
        - nginx

    - name: ensure nginx is configured
      template:
        src: nginx.conf
        dest: /etc/nginx/conf.d/

    - name: ensure nginx has been restarted
      service:
        name: nginx
        state: restarted

    - name: ensure app code is on the box in /mnt
      template:
        src: node-app.js
        dest: "{{node_app_path}}"

    - name: ensure location of nodejs is known
      command: which nodejs
      register: which_nodejs

    - name: ensure upstart script for app is in place
      template:
        src: node-app.conf
        dest: /etc/init

    - name: start app
      service:
        name: node-app
        state: restarted
