- hosts: all
  become: yes
  become_method: sudo
  vars:
    packages:
      - nodejs
      - ruby
      - nginx
  tasks:
    - name: ensure apt cache is updated
      apt:

    - name: ensure apt packages are installed
      apt:

    - name: ensure nginx is configured
      template:

    - name: ensure nginx has been restarted
      service:

    - name: ensure app code is on the box in /mnt
      copy:
      # hint, check out with_fileglob
